pub const MPU_OUTPUT_VOLTAGE: f32 = 3.3;

pub const VOLTAGE_DIVIDER_BATTERY_RESISTOR_BEFORE_PROBE: f32 = 13e3;
pub const VOLTAGE_DIVIDER_BATTERY_RESISTOR_AFTER_PROBE: f32 = 2e3;

pub const VOLTAGE_DIVIDER_PRESSURE_SENSOR_RESISTOR_BEFORE_PROBE: f32 = 13.7e3; //13e3;
pub const VOLTAGE_DIVIDER_PRESSURE_SENSOR_RESISTOR_AFTER_PROBE: f32 = 1150.0; //1e3;

pub const PRESSURE_SENSOR_OUTPUT_RESISTOR_AFTER_PROBE: f32 = 130.0;

pub const PRESSURE_SENSOR_MAXIMUM_HEIGHT: f32 = 5.0;
