name: Rust Lint

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - master

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        items: [ { path: "crates/app", target: riscv32imac-unknown-none-elf }, { path: "crates/service", target: "x86_64-unknown-linux-gnu" } ]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@a54c7afa936fefeb4456b2dd8068152669aa8203 # v1
        with:
          target: ${{ matrix.items.target }}
          toolchain: stable
      - name: Enable caching
        uses: Swatinem/rust-cache@f0deed1e0edfc6a9be95417288c0e1099b1eeec3 # v2
      - working-directory: ${{ matrix.items.path }}
        run: cargo check

  rustfmt:
    name: rustfmt
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        items: [ { path: "crates/app", target: riscv32imac-unknown-none-elf }, { path: "crates/service", target: "x86_64-unknown-linux-gnu" } ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@a54c7afa936fefeb4456b2dd8068152669aa8203 # v1
        with:
          target: ${{ matrix.items.target }}
          toolchain: stable
          components: rustfmt
      - name: Enable caching
        uses: Swatinem/rust-cache@f0deed1e0edfc6a9be95417288c0e1099b1eeec3 # v2
      - name: Check formatting
        working-directory: ${{ matrix.items.path }}
        run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    permissions:
      checks: write
    strategy:
      fail-fast: false
      matrix:
        items: [ { path: "crates/app", target: riscv32imac-unknown-none-elf }, { path: "crates/service", target: "x86_64-unknown-linux-gnu" } ]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@a54c7afa936fefeb4456b2dd8068152669aa8203 # v1
        with:
          target: ${{ matrix.items.target }}
          toolchain: stable
          components: clippy
      - name: Enable caching
        uses: Swatinem/rust-cache@f0deed1e0edfc6a9be95417288c0e1099b1eeec3 # v2
      - name: Clippy Output
        working-directory: ${{ matrix.items.path }}
        run: cargo clippy --no-deps --all-features


  # cargo-semver-checks-action doesn't currently support specifying a base version manually.
  #
  # verify-semver:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Set up Rust
  #       uses: actions/checkout@v2
  #     - name: Install Rust
  #       uses: actions-rs/toolchain@v1
  #       with:
  #         profile: minimal
  #         toolchain: stable
  #     - name: Check semver
  #       uses: obi1kenobi/cargo-semver-checks-action@48f4ef7da6d907d69d18249e0ba79aa98c61b9db

  # Cargo deny has an issue with 'private' dependencies that have no license. See here: https://github.com/EmbarkStudios/cargo-deny/issues/736
  #
  # cargo-deny:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       checks:
  #         - advisories
  #         - bans licenses sources
  #       items: [ { path: "crates/app", target: riscv32imac-unknown-none-elf }, { path: "crates/service", target: "x86_64-unknown-linux-gnu" } ]

  #   # Prevent sudden announcement of a new advisory from failing ci:
  #   continue-on-error: ${{ matrix.checks == 'advisories' }}

  #   steps:
  #   - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
  #   - uses: EmbarkStudios/cargo-deny-action@8371184bd11e21dcf8ac82ebf8c9c9f74ebf7268 # v2
  #     with:
  #       command: check ${{ matrix.checks }}
  #       manifest-path: ${{ matrix.items.path }}/Cargo.toml
